# Generated by Django 5.1.4 on 2025-01-01 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('military_unit_number', models.CharField(max_length=100, verbose_name='Номер військової частини')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('commander_name', models.CharField(max_length=255, verbose_name='ПІБ командира')),
                ('request_text', models.TextField(verbose_name='Запит')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_clarification', 'Needs Clarification'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='Коментар менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
