# Generated by Django 5.1.4 on 2025-01-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0003_alter_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
    ]
