# Generated by Django 5.1.4 on 2025-01-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0004_remove_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='commander_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='comment',
        ),
    ]
