# Generated by Django 5.1.4 on 2025-01-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0007_request_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_clarification', 'Needs Clarification'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
